### PR TITLE
Update modman to work

### PR DESCRIPTION
**Pull request by kimtiago**
Update modman to work

### CODE REVIEW

**Comment by tig-michielgerritsen** [comment]
Hi Kimtiago,

Thank you for your pull request. We are not sure what your pull request fixes, as the modman should be fine. Can you explain this further?

**Comment by kimtiago** [comment]
i'm using modgit, who uses modman file to work.
in the file has no information where the files should be copy. So, modgit puts the files in magento root folder. Check this images. First, its before install, look at my magento folder strutucture.

screen shot 01-19-17 at 12 00 pm

Now look after install the module

screen shot 01-19-17 at 12 00 pm 001

i use modgit with more than 20 extensions in github and tinypng exntension it's the unique i have this problem. I investigated and discover the problem is in modman file, i fixed it and did a pull request.

**Comment by tig-michielgerritsen** [comment]
Hi Kimtiago,

Thanks for you explanation. We did investigate Modgit as we never heard of this, and we decided we are not going to support this. Modman is way nicer solution to achieve almost the same. Thanks for your efforts though!

**Comment by raphaelsuzuki** [comment]
Hi @tig-michielgerritsen,

I second this pull request and ask you to reconsider implementing the changes described here. Modgit is a very popular way to add modules to a Magento installation which work regardless of symlinks, a feature that has been disabled by default on latest version of the ecommerce platform. Also, the same issue described here seems to be affecting Magento Composer Installer compatibility with modman:

https://github.com/Cotya/magento-composer-installer/blob/master/doc/Mapping.md

https://github.com/caciobanu/improved-magento-layered-navigation/commit/ec0b8a9f4820e535211b24fef6b9babae958cd28

You actually don't need to write anything different in order to support it, and it's not even dependent of a .modman file to work, but it does try to parse one if present, since it is compatible with modman modules. I personally haven't found any other issue beside this one. However, it must have the correct syntax of `<link target> <link location>` as it is defined by modman's own manual (modman itself won't break with a syntax lacking `<link location>`):

https://github.com/colinmollenhour/modman/wiki/Tutorial

Maybe the proposed changes to the file were a bit too verbose (since the module don't have any special directory structure, it was just a matter of duplicating the content of each line separated by a space), but it is an easy fix that will provide a whole lot of compatibility without side effects.

**Pull request closed without merging**
